#!/usr/bin/env python3
"""
Create a focused diagnostic report from locally-downloaded W&B run evidence.

This reads:
  analysis/wandb_evidence/<run_id>/history.parquet
  analysis/wandb_evidence/<run_id>/config_api.yaml

and writes:
  analysis/wandb_evidence/diagnostics/*.md
  analysis/wandb_evidence/diagnostics/plots/*.png
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import pandas as pd
import yaml


@dataclass(frozen=True)
class RunSpec:
    run_id: str
    label: str


def _read_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        obj = yaml.safe_load(f)
    return obj if isinstance(obj, dict) else {}


def _get_path(d: dict[str, Any], dotted: str) -> Any:
    cur: Any = d
    for part in dotted.split("."):
        if not isinstance(cur, dict):
            return None
        if part not in cur:
            return None
        cur = cur[part]
    return cur


def _first_last_non_nan(series: pd.Series) -> tuple[Any, Any]:
    s = series.dropna()
    if s.empty:
        return None, None
    return s.iloc[0], s.iloc[-1]


def _ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def _plot_series(ax, df: pd.DataFrame, *, x: str, y: str, label: str) -> None:
    if x not in df.columns or y not in df.columns:
        return
    sub = df[[x, y]].dropna()
    if sub.empty:
        return
    ax.plot(sub[x], sub[y], label=label, linewidth=1.5)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--evidence-root", default="analysis/wandb_evidence")
    ap.add_argument(
        "--runs",
        nargs="+",
        default=["px0sxz3v:guess-first (failing)", "2qpf3534:baseline (reference)"],
        help="Run specs formatted as RUN_ID:LABEL",
    )
    args = ap.parse_args()

    evidence_root = Path(args.evidence_root)
    out_root = evidence_root / "diagnostics"
    plots_dir = out_root / "plots"
    _ensure_dir(out_root)
    _ensure_dir(plots_dir)

    runs: list[RunSpec] = []
    for item in args.runs:
        if ":" in item:
            run_id, label = item.split(":", 1)
        else:
            run_id, label = item, item
        runs.append(RunSpec(run_id=run_id.strip(), label=label.strip()))

    # Load histories + configs.
    histories: dict[str, pd.DataFrame] = {}
    configs: dict[str, dict[str, Any]] = {}

    for rs in runs:
        hist_path = evidence_root / rs.run_id / "history.parquet"
        cfg_path = evidence_root / rs.run_id / "config_api.yaml"
        histories[rs.run_id] = pd.read_parquet(hist_path)
        configs[rs.run_id] = _read_yaml(cfg_path)

    # Focused metrics summary.
    train_cols = [
        "critic/score/mean",
        "critic/rewards/mean",
        "actor/entropy",
        "actor/lr",
        "actor/pg_loss",
        "actor/ppo_kl",
        "forced_prefix/apply_prob",
        "forced_prefix/forced_seq_frac",
        "forced_prefix/train_reward_mean_forced",
        "forced_prefix/train_reward_mean_free",
    ]
    val_cols = [
        # `format_reward` is 0/1; mean@1 is the true "format-valid rate".
        "val-aux/local/chess_puzzles/format_reward/mean@1",
        "val-aux/local/chess_puzzles/score/mean@1",
        "val-aux/local/chess_puzzles/coverage/mean@1",
        "val-core/local/chess_puzzles/acc/mean@1",
    ]

    summary_rows: list[dict[str, Any]] = []
    for rs in runs:
        df = histories[rs.run_id]
        row: dict[str, Any] = {"run_id": rs.run_id, "label": rs.label}
        row["steps"] = int(df["_step"].max()) if "_step" in df.columns and pd.notna(df["_step"].max()) else None
        for col in train_cols:
            if col not in df.columns:
                continue
            first, last = _first_last_non_nan(df[col])
            row[f"{col}__first"] = first
            row[f"{col}__last"] = last

        # Validation points
        val_points = 0
        if val_cols[0] in df.columns:
            val_points = int(df[val_cols[0]].notna().sum())
        row["val_points"] = val_points
        for col in val_cols:
            if col not in df.columns:
                continue
            first, last = _first_last_non_nan(df[col])
            row[f"{col}__first"] = first
            row[f"{col}__last"] = last
        summary_rows.append(row)

    summary_df = pd.DataFrame(summary_rows).sort_values("run_id")
    summary_df.to_csv(out_root / "metrics_summary.csv", index=False)

    # Markdown summary (human-readable).
    md_lines = []
    md_lines.append("# W&B Diagnostics (from local evidence)\n")
    md_lines.append("Generated by `python3 scripts/diagnose_wandb_runs.py`.\n")
    md_lines.append("## Metrics summary (first/last non-NaN)\n")
    md_lines.append("See `analysis/wandb_evidence/diagnostics/metrics_summary.csv` for the full table.\n")
    for rs in runs:
        r = summary_df[summary_df["run_id"] == rs.run_id].iloc[0].to_dict()
        md_lines.append(f"### {rs.run_id} — {rs.label}\n")
        md_lines.append(f"- steps: {r.get('steps')}\n")
        md_lines.append(f"- val points logged: {r.get('val_points')}\n")
        md_lines.append(f"- train `critic/score/mean`: {r.get('critic/score/mean__first')} → {r.get('critic/score/mean__last')}\n")
        md_lines.append(f"- train `forced_prefix/apply_prob`: {r.get('forced_prefix/apply_prob__first')} → {r.get('forced_prefix/apply_prob__last')}\n")
        md_lines.append(
            f"- train `forced_prefix/train_reward_mean_forced`: {r.get('forced_prefix/train_reward_mean_forced__first')} → {r.get('forced_prefix/train_reward_mean_forced__last')}\n"
        )
        md_lines.append(
            f"- train `forced_prefix/train_reward_mean_free`: {r.get('forced_prefix/train_reward_mean_free__first')} → {r.get('forced_prefix/train_reward_mean_free__last')}\n"
        )
        md_lines.append(f"- train `actor/entropy`: {r.get('actor/entropy__first')} → {r.get('actor/entropy__last')}\n")
        md_lines.append(f"- val `{val_cols[0]}`: {r.get(val_cols[0] + '__first')} → {r.get(val_cols[0] + '__last')}\n")
        md_lines.append(f"- val `coverage/mean@1`: {r.get(val_cols[2] + '__first')} → {r.get(val_cols[2] + '__last')}\n")
        md_lines.append("\n")

    (out_root / "metrics_summary.md").write_text("".join(md_lines), encoding="utf-8")

    # Plots: train reward + forced prefix schedule, entropy, and val metrics.
    def save_fig(name: str) -> None:
        p = plots_dir / name
        plt.tight_layout()
        plt.savefig(p, dpi=160)
        plt.close()

    # Train reward over steps.
    plt.figure(figsize=(10, 4))
    ax = plt.gca()
    for rs in runs:
        _plot_series(ax, histories[rs.run_id], x="_step", y="critic/score/mean", label=rs.label)
    ax.set_title("Train reward (critic/score/mean)")
    ax.set_xlabel("step")
    ax.set_ylabel("mean reward")
    ax.legend()
    ax.grid(True, alpha=0.3)
    save_fig("train_reward.png")

    # Forced-prefix schedule vs reward components.
    plt.figure(figsize=(10, 4))
    ax = plt.gca()
    for rs in runs:
        _plot_series(ax, histories[rs.run_id], x="_step", y="forced_prefix/apply_prob", label=f"{rs.label} apply_prob")
        _plot_series(
            ax, histories[rs.run_id], x="_step", y="forced_prefix/forced_seq_frac", label=f"{rs.label} forced_seq_frac"
        )
    ax.set_title("Forced-prefix schedule / composition")
    ax.set_xlabel("step")
    ax.set_ylabel("fraction / probability")
    ax.legend()
    ax.grid(True, alpha=0.3)
    save_fig("forced_prefix_schedule.png")

    # Forced vs free train reward (when available).
    plt.figure(figsize=(10, 4))
    ax = plt.gca()
    for rs in runs:
        _plot_series(
            ax,
            histories[rs.run_id],
            x="_step",
            y="forced_prefix/train_reward_mean_forced",
            label=f"{rs.label} forced",
        )
        _plot_series(
            ax,
            histories[rs.run_id],
            x="_step",
            y="forced_prefix/train_reward_mean_free",
            label=f"{rs.label} free",
        )
    ax.set_title("Train reward split: forced vs free (mean)")
    ax.set_xlabel("step")
    ax.set_ylabel("mean reward")
    ax.legend()
    ax.grid(True, alpha=0.3)
    save_fig("train_reward_forced_vs_free.png")

    # Entropy.
    plt.figure(figsize=(10, 4))
    ax = plt.gca()
    for rs in runs:
        _plot_series(ax, histories[rs.run_id], x="_step", y="actor/entropy", label=rs.label)
    ax.set_title("Actor entropy")
    ax.set_xlabel("step")
    ax.set_ylabel("entropy")
    ax.legend()
    ax.grid(True, alpha=0.3)
    save_fig("actor_entropy.png")

    # Validation format + coverage (sparse points).
    plt.figure(figsize=(10, 4))
    ax = plt.gca()
    for rs in runs:
        df = histories[rs.run_id]
        y = "val-aux/local/chess_puzzles/coverage/mean@1"
        if y in df.columns:
            sub = df[["_step", y]].dropna()
            if not sub.empty:
                ax.plot(sub["_step"], sub[y], marker="o", linewidth=1.5, label=rs.label)
    ax.set_title("Validation: exact-match coverage/acc (mean@1)")
    ax.set_xlabel("step")
    ax.set_ylabel("coverage / acc")
    ax.legend()
    ax.grid(True, alpha=0.3)
    save_fig("val_coverage.png")

    # Validation format-valid rate.
    plt.figure(figsize=(10, 4))
    ax = plt.gca()
    for rs in runs:
        df = histories[rs.run_id]
        y = "val-aux/local/chess_puzzles/format_reward/mean@1"
        if y in df.columns:
            sub = df[["_step", y]].dropna()
            if not sub.empty:
                ax.plot(sub["_step"], sub[y], marker="o", linewidth=1.5, label=rs.label)
    ax.set_title("Validation: format-valid rate (format_reward mean@1)")
    ax.set_xlabel("step")
    ax.set_ylabel("format-valid rate")
    ax.legend()
    ax.grid(True, alpha=0.3)
    save_fig("val_format_valid.png")

    # Focused config diff for key knobs.
    interesting = [
        "data.train_files",
        "data.val_files",
        "data.max_prompt_length",
        "data.max_response_length",
        "data.train_batch_size",
        "actor_rollout_ref.rollout.n",
        "actor_rollout_ref.rollout.response_length",
        "actor_rollout_ref.rollout.val_kwargs.temperature",
        "actor_rollout_ref.rollout.val_kwargs.top_p",
        "actor_rollout_ref.actor.optim.lr",
        "actor_rollout_ref.actor.optim.lr_scheduler_type",
        "actor_rollout_ref.actor.optim.warmup_style",
        "actor_rollout_ref.actor.ppo_mini_batch_size",
        "actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu",
        "actor_rollout_ref.actor.use_kl_loss",
        "actor_rollout_ref.actor.kl_loss_coef",
        "actor_rollout_ref.actor.entropy_coeff",
        "algorithm.adv_estimator",
        "algorithm.use_kl_in_reward",
        "forced_prefix.enable",
        "forced_prefix.apply_prob_start",
        "forced_prefix.apply_prob_end",
        "forced_prefix.annealing_frac",
        "forced_prefix.move_temperature",
        "forced_prefix.prefix_template",
        "trainer.test_freq",
        "trainer.val_before_train",
        "trainer.total_training_steps",
    ]
    cfg_rows = []
    for dotted in interesting:
        row = {"key": dotted}
        for rs in runs:
            row[rs.run_id] = _get_path(configs[rs.run_id], dotted)
        cfg_rows.append(row)
    cfg_df = pd.DataFrame(cfg_rows)
    cfg_df.to_csv(out_root / "config_key_diff.csv", index=False)

    cfg_md = []
    cfg_md.append("# Key config diff (from config_api.yaml)\n\n")
    cfg_md.append("Generated by `python3 scripts/diagnose_wandb_runs.py`.\n\n")
    cfg_md.append("Table is intentionally limited to a small set of knobs relevant to training dynamics.\n\n")
    cfg_md.append(f"Runs compared: {', '.join([rs.run_id for rs in runs])}\n\n")
    cfg_md.append("| key | " + " | ".join([rs.run_id for rs in runs]) + " |\n")
    cfg_md.append("|---" + "|---" * len(runs) + "|\n")
    for _, r in cfg_df.iterrows():
        vals = []
        for rs in runs:
            v = r.get(rs.run_id)
            if isinstance(v, (dict, list)):
                v = json.dumps(v, sort_keys=True)
            vals.append(str(v))
        cfg_md.append("| " + str(r["key"]) + " | " + " | ".join(vals) + " |\n")
    (out_root / "config_key_diff.md").write_text("".join(cfg_md), encoding="utf-8")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
