#!/usr/bin/env bash

set -euo pipefail

# Iterative (allowed_move_elim; optional online self-play) diversity launcher for Qwen2.5-3B.
# Default mode is a 1-step smoke run that disables validation/eval/checkpoint saves.
#
# Usage:
#   ./launch_iterative_diversity_smoke_qwen3b.sh
#   VARIANT=obe_batch ./launch_iterative_diversity_smoke_qwen3b.sh
#   VARIANT=gapo WAIT=0 ./launch_iterative_diversity_smoke_qwen3b.sh
#   VARIANT=distinct_k SMOKE=1 ./launch_iterative_diversity_smoke_qwen3b.sh
#   VARIANT=all SMOKE=1 WAIT=1 ./launch_iterative_diversity_smoke_qwen3b.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

VARIANT="${VARIANT:-all}"  # obe_batch|gapo|distinct_k|all
WAIT="${WAIT:-1}"
SMOKE="${SMOKE:-1}"

# Fixed model envelope (aligned with recent Qwen3B launchers).
MODEL_PATH="${MODEL_PATH:-/projects/a5l/ziyan/models/Qwen/Qwen2.5-3B-Instruct}"
MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-1536}"
MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-2000}"
ROLLOUT_N="${ROLLOUT_N:-16}"

# Dataset / reward setup for selection framing.
CHESS_DATA_DIR="${CHESS_DATA_DIR:-data/chess_puzzles_chessr1_aligned_sharded_ours}"
CHESS_RL_VAL_FILES="${CHESS_RL_VAL_FILES:-[data/chess_puzzles_chessr1_aligned_sharded_ours/test.parquet,data/chess_puzzles_chessr1_aligned_sharded_ours/test_shuffled_legal_moves.parquet]}"
CHESS_REWARD_FN="${CHESS_REWARD_FN:-expected_score_wdl_vs_best}"
CHESS_RL_DATA_SEED="${CHESS_RL_DATA_SEED:-null}"

# Iterative online-play + allowed-move-elim knobs.
CHESS_SELF_PLAY_ENABLE="${CHESS_SELF_PLAY_ENABLE:-False}"
CHESS_SELF_PLAY_DUMP_STEPS="${CHESS_SELF_PLAY_DUMP_STEPS:-[1]}"
CHESS_ALLOWED_MOVE_ELIM_ENABLE="${CHESS_ALLOWED_MOVE_ELIM_ENABLE:-True}"
CHESS_ALLOWED_MOVE_ELIM_TEMPLATE_PATH="${CHESS_ALLOWED_MOVE_ELIM_TEMPLATE_PATH:-recipe/chess/prompt_templates/select_prompt.jinja}"
CHESS_ALLOWED_MOVE_ELIM_UID_MODE="${CHESS_ALLOWED_MOVE_ELIM_UID_MODE:-per_round}"
CHESS_ALLOWED_MOVE_ELIM_NO_SUCCESS_POLICY="${CHESS_ALLOWED_MOVE_ELIM_NO_SUCCESS_POLICY:-accept_last}"
CHESS_ALLOWED_MOVE_ELIM_R_MAX_START="${CHESS_ALLOWED_MOVE_ELIM_R_MAX_START:-4}"
CHESS_ALLOWED_MOVE_ELIM_R_MAX_END="${CHESS_ALLOWED_MOVE_ELIM_R_MAX_END:-4}"
CHESS_ALLOWED_MOVE_ELIM_ANNEAL_FRAC="${CHESS_ALLOWED_MOVE_ELIM_ANNEAL_FRAC:-1.0}"
CHESS_ALLOWED_MOVE_ELIM_GROUP_REWARD_RANGE_MIN="${CHESS_ALLOWED_MOVE_ELIM_GROUP_REWARD_RANGE_MIN:-0.0}"
CHESS_ALLOWED_MOVE_ELIM_GROUP_REWARD_RANGE_DUMP_MAX_GROUPS="${CHESS_ALLOWED_MOVE_ELIM_GROUP_REWARD_RANGE_DUMP_MAX_GROUPS:-16}"
CHESS_ALLOWED_MOVE_ELIM_DIVERSITY_WHEN_NO_OPTIMAL="${CHESS_ALLOWED_MOVE_ELIM_DIVERSITY_WHEN_NO_OPTIMAL:-True}"

# Keep baseline/global pass@k off; optional conditional pass@k is controlled by env.
CHESS_PASS_K_TRAINING="${CHESS_PASS_K_TRAINING:-False}"
CHESS_PASS_K="${CHESS_PASS_K:-1}"
CHESS_ALLOWED_MOVE_ELIM_PASS_K_WHEN_NO_OPTIMAL="${CHESS_ALLOWED_MOVE_ELIM_PASS_K_WHEN_NO_OPTIMAL:-False}"
CHESS_ALLOWED_MOVE_ELIM_PASS_K_K="${CHESS_ALLOWED_MOVE_ELIM_PASS_K_K:-4}"

# Diversity controls (methods differ by variant; lambda/k are shared defaults).
CHESS_DIVERSITY_LAMBDA="${CHESS_DIVERSITY_LAMBDA:-0.25}"
CHESS_DIVERSITY_DISTINCT_K="${CHESS_DIVERSITY_DISTINCT_K:-4}"
CHESS_DIVERSITY_INCLUDE_BASE_ADVANTAGE="${CHESS_DIVERSITY_INCLUDE_BASE_ADVANTAGE:-True}"

# Batch + trainer envelope.
CHESS_RL_TRAIN_BATCH_SIZE="${CHESS_RL_TRAIN_BATCH_SIZE:-128}"
TOTAL_EPOCHS="${TOTAL_EPOCHS:-1}"
CHESS_RL_TENSOR_MODEL_PARALLEL_SIZE="${CHESS_RL_TENSOR_MODEL_PARALLEL_SIZE:-1}"
CHESS_RL_PPO_MICRO_BATCH_SIZE="${CHESS_RL_PPO_MICRO_BATCH_SIZE:-8}"
CHESS_RL_ROLLOUT_LOGPROB_MICRO_BATCH_SIZE="${CHESS_RL_ROLLOUT_LOGPROB_MICRO_BATCH_SIZE:-16}"
CHESS_RL_REF_LOGPROB_MICRO_BATCH_SIZE="${CHESS_RL_REF_LOGPROB_MICRO_BATCH_SIZE:-16}"
CHESS_RL_WANDB_MODE="${CHESS_RL_WANDB_MODE:-online}"
CHESS_RL_USE_KL_LOSS="${CHESS_RL_USE_KL_LOSS:-True}"
CHESS_RL_MODEL_ONLY_CKPT="${CHESS_RL_MODEL_ONLY_CKPT:-True}"
CHESS_RL_TRAINER_RESUME_MODE="${CHESS_RL_TRAINER_RESUME_MODE:-disable}"

# Optional HF upload controls.
CHESS_RL_HF_UPLOAD_ENABLE="${CHESS_RL_HF_UPLOAD_ENABLE:-False}"
CHESS_RL_HF_CKPT_REPO_ID="${CHESS_RL_HF_CKPT_REPO_ID:-Gabr1e11/a_lot_of_models}"
CHESS_RL_HF_TOKEN_FILE="${CHESS_RL_HF_TOKEN_FILE:-${HOME}/.hf_token}"

if [ "${CHESS_ALLOWED_MOVE_ELIM_ENABLE}" != "True" ]; then
  echo "ERROR: this launcher requires CHESS_ALLOWED_MOVE_ELIM_ENABLE=True (got '${CHESS_ALLOWED_MOVE_ELIM_ENABLE}')." >&2
  exit 1
fi
if [ "${CHESS_ALLOWED_MOVE_ELIM_DIVERSITY_WHEN_NO_OPTIMAL}" != "True" ]; then
  echo "ERROR: this launcher requires CHESS_ALLOWED_MOVE_ELIM_DIVERSITY_WHEN_NO_OPTIMAL=True (got '${CHESS_ALLOWED_MOVE_ELIM_DIVERSITY_WHEN_NO_OPTIMAL}')." >&2
  exit 1
fi
if [ "${CHESS_PASS_K_TRAINING}" != "False" ]; then
  echo "ERROR: this launcher requires CHESS_PASS_K_TRAINING=False (got '${CHESS_PASS_K_TRAINING}')." >&2
  exit 1
fi

if [ "${SMOKE}" = "1" ]; then
  TOTAL_TRAINING_STEPS="1"
  VAL_BEFORE_TRAIN="False"
  TRAINER_TEST_FREQ="-1"
  CHESS_RL_TRAINER_SAVE_FREQ="-1"
  CHESS_RL_FULL_EVAL_FREQ="-1"
  RUN_KIND="smoke"
else
  if [ "${CHESS_SELF_PLAY_ENABLE}" = "True" ]; then
    if [ -z "${CHESS_RL_TOTAL_TRAINING_STEPS:-}" ] || [ "${CHESS_RL_TOTAL_TRAINING_STEPS}" = "null" ]; then
      echo "ERROR: CHESS_SELF_PLAY_ENABLE=True requires CHESS_RL_TOTAL_TRAINING_STEPS=<int> (got '${CHESS_RL_TOTAL_TRAINING_STEPS:-<unset>}')." >&2
      exit 1
    fi
    TOTAL_TRAINING_STEPS="${CHESS_RL_TOTAL_TRAINING_STEPS}"
  else
    TOTAL_TRAINING_STEPS="${CHESS_RL_TOTAL_TRAINING_STEPS:-null}"
  fi
  VAL_BEFORE_TRAIN="True"
  TRAINER_TEST_FREQ="${TRAINER_TEST_FREQ:-40}"
  CHESS_RL_TRAINER_SAVE_FREQ="${CHESS_RL_TRAINER_SAVE_FREQ:-80}"
  CHESS_RL_FULL_EVAL_FREQ="${CHESS_RL_FULL_EVAL_FREQ:-80}"
  RUN_KIND="full"
fi

SBATCH_WAIT_ARGS=()
if [ "${WAIT}" = "1" ]; then
  SBATCH_WAIT_ARGS+=(--wait)
fi

submit_one() {
  local label="$1"
  local diversity_method="$2"
  local run_tag="cr1_iterdiv_${label}_${RUN_KIND}_$(date +%Y%m%d_%H%M%S)"
  local job_name="cr1-iterdiv-${label}-${RUN_KIND}"

  echo "[INFO] submit ${label}"
  echo "[INFO]   RUN_TAG=${run_tag}"
  echo "[INFO]   JOB_NAME=${job_name}"
  echo "[INFO]   VARIANT_METHOD=${diversity_method}"
  echo "[INFO]   SMOKE=${SMOKE} WAIT=${WAIT}"
  echo "[INFO]   TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS}"
  echo "[INFO]   CHESS_SELF_PLAY_ENABLE=${CHESS_SELF_PLAY_ENABLE}"
  echo "[INFO]   CHESS_ALLOWED_MOVE_ELIM_ENABLE=${CHESS_ALLOWED_MOVE_ELIM_ENABLE}"
  echo "[INFO]   CHESS_ALLOWED_MOVE_ELIM_PASS_K_WHEN_NO_OPTIMAL=${CHESS_ALLOWED_MOVE_ELIM_PASS_K_WHEN_NO_OPTIMAL}"
  echo "[INFO]   CHESS_ALLOWED_MOVE_ELIM_DIVERSITY_WHEN_NO_OPTIMAL=${CHESS_ALLOWED_MOVE_ELIM_DIVERSITY_WHEN_NO_OPTIMAL}"
  echo "[INFO]   CHESS_DIVERSITY_LAMBDA=${CHESS_DIVERSITY_LAMBDA}"
  echo "[INFO]   CHESS_DIVERSITY_DISTINCT_K=${CHESS_DIVERSITY_DISTINCT_K}"

  CHESS_RL_VAL_FILES="${CHESS_RL_VAL_FILES}" \
  CHESS_SELF_PLAY_DUMP_STEPS="${CHESS_SELF_PLAY_DUMP_STEPS}" \
  sbatch "${SBATCH_WAIT_ARGS[@]}" \
    --nodes=1 --ntasks=1 --ntasks-per-node=1 --gres=gpu:4 --cpus-per-task=144 \
    --partition=workq --account=brics.a5l --job-name="${job_name}" \
    --export=ALL,CHESS_RL_VERL_BASE_DIR=/projects/a5l/ziyan/chess_rl_outputs/${run_tag},CHESS_DATA_DIR=${CHESS_DATA_DIR},CHESS_RL_FULL_EVAL_PROMPT_TEMPLATE_PATH=recipe/chess/prompt_templates/select_prompt.jinja,USE_HARD_DATASET=False,CHESS_REWARD_FN=${CHESS_REWARD_FN},CHESS_RL_TRAIN_BATCH_SIZE=${CHESS_RL_TRAIN_BATCH_SIZE},TOTAL_EPOCHS=${TOTAL_EPOCHS},CHESS_SELF_PLAY_ENABLE=${CHESS_SELF_PLAY_ENABLE},CHESS_ALLOWED_MOVE_ELIM_ENABLE=${CHESS_ALLOWED_MOVE_ELIM_ENABLE},CHESS_ALLOWED_MOVE_ELIM_TEMPLATE_PATH=${CHESS_ALLOWED_MOVE_ELIM_TEMPLATE_PATH},CHESS_ALLOWED_MOVE_ELIM_UID_MODE=${CHESS_ALLOWED_MOVE_ELIM_UID_MODE},CHESS_ALLOWED_MOVE_ELIM_NO_SUCCESS_POLICY=${CHESS_ALLOWED_MOVE_ELIM_NO_SUCCESS_POLICY},CHESS_ALLOWED_MOVE_ELIM_R_MAX_START=${CHESS_ALLOWED_MOVE_ELIM_R_MAX_START},CHESS_ALLOWED_MOVE_ELIM_R_MAX_END=${CHESS_ALLOWED_MOVE_ELIM_R_MAX_END},CHESS_ALLOWED_MOVE_ELIM_ANNEAL_FRAC=${CHESS_ALLOWED_MOVE_ELIM_ANNEAL_FRAC},CHESS_ALLOWED_MOVE_ELIM_GROUP_REWARD_RANGE_MIN=${CHESS_ALLOWED_MOVE_ELIM_GROUP_REWARD_RANGE_MIN},CHESS_ALLOWED_MOVE_ELIM_GROUP_REWARD_RANGE_DUMP_MAX_GROUPS=${CHESS_ALLOWED_MOVE_ELIM_GROUP_REWARD_RANGE_DUMP_MAX_GROUPS},CHESS_ALLOWED_MOVE_ELIM_PASS_K_WHEN_NO_OPTIMAL=${CHESS_ALLOWED_MOVE_ELIM_PASS_K_WHEN_NO_OPTIMAL},CHESS_ALLOWED_MOVE_ELIM_PASS_K_K=${CHESS_ALLOWED_MOVE_ELIM_PASS_K_K},CHESS_ALLOWED_MOVE_ELIM_DIVERSITY_WHEN_NO_OPTIMAL=${CHESS_ALLOWED_MOVE_ELIM_DIVERSITY_WHEN_NO_OPTIMAL},FILTER_GROUPS_ENABLE=False,CHESS_RL_TENSOR_MODEL_PARALLEL_SIZE=${CHESS_RL_TENSOR_MODEL_PARALLEL_SIZE},CHESS_RL_PPO_MICRO_BATCH_SIZE=${CHESS_RL_PPO_MICRO_BATCH_SIZE},CHESS_RL_ROLLOUT_LOGPROB_MICRO_BATCH_SIZE=${CHESS_RL_ROLLOUT_LOGPROB_MICRO_BATCH_SIZE},CHESS_RL_REF_LOGPROB_MICRO_BATCH_SIZE=${CHESS_RL_REF_LOGPROB_MICRO_BATCH_SIZE},TRAINER_TEST_FREQ=${TRAINER_TEST_FREQ},MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH},MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH},ROLLOUT_N=${ROLLOUT_N},MODEL_PATH=${MODEL_PATH},CHESS_RL_WANDB_MODE=${CHESS_RL_WANDB_MODE},CHESS_RL_TRAINER_SAVE_FREQ=${CHESS_RL_TRAINER_SAVE_FREQ},CHESS_RL_FULL_EVAL_FREQ=${CHESS_RL_FULL_EVAL_FREQ},CHESS_RL_USE_KL_LOSS=${CHESS_RL_USE_KL_LOSS},CHESS_PASS_K_TRAINING=${CHESS_PASS_K_TRAINING},CHESS_PASS_K=${CHESS_PASS_K},CHESS_DIVERSITY_ENABLE=True,CHESS_DIVERSITY_METHOD=${diversity_method},CHESS_DIVERSITY_LAMBDA=${CHESS_DIVERSITY_LAMBDA},CHESS_DIVERSITY_DISTINCT_K=${CHESS_DIVERSITY_DISTINCT_K},CHESS_DIVERSITY_INCLUDE_BASE_ADVANTAGE=${CHESS_DIVERSITY_INCLUDE_BASE_ADVANTAGE},CHESS_RL_DATA_SEED=${CHESS_RL_DATA_SEED},CHESS_RL_TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS},VAL_BEFORE_TRAIN=${VAL_BEFORE_TRAIN},FORCED_PREFIX_ENABLE=False,CHESS_RL_MODEL_ONLY_CKPT=${CHESS_RL_MODEL_ONLY_CKPT},CHESS_RL_TRAINER_RESUME_MODE=${CHESS_RL_TRAINER_RESUME_MODE},CHESS_RL_HF_UPLOAD_ENABLE=${CHESS_RL_HF_UPLOAD_ENABLE},CHESS_RL_HF_CKPT_REPO_ID=${CHESS_RL_HF_CKPT_REPO_ID},CHESS_RL_HF_TOKEN_FILE=${CHESS_RL_HF_TOKEN_FILE} \
    ./sbatch_train_chess_gh200.slurm
}

case "${VARIANT}" in
  obe|obe_batch)
    submit_one obe obe_batch
    ;;
  gapo)
    submit_one gapo gapo
    ;;
  distinct|distinct_k)
    submit_one distinct distinct_k
    ;;
  all)
    submit_one obe obe_batch
    submit_one gapo gapo
    submit_one distinct distinct_k
    ;;
  *)
    echo "Unknown VARIANT='${VARIANT}'. Expected obe_batch|gapo|distinct_k|all." >&2
    exit 1
    ;;
esac
