#!/usr/bin/env bash
set -euo pipefail

# Convenience wrapper to submit the A–E SFT forced-prefix ablation on GH200.
#
# Example:
#   bash ./submit_sft_prefix_ablation_gh200.bash
#
# Smoke:
#   CHESS_SFT_SMOKE=1 bash ./submit_sft_prefix_ablation_gh200.bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

SBATCH_SCRIPT="${CHESS_SFT_SBATCH_SCRIPT:-${SCRIPT_DIR}/sbatch_sft_prefix_ablation_gh200.slurm}"
if [ ! -f "${SBATCH_SCRIPT}" ]; then
  echo "[ERROR] Missing sbatch script: ${SBATCH_SCRIPT}" >&2
  exit 1
fi

BASE_EVAL_SBATCH_SCRIPT="${CHESS_SFT_BASE_EVAL_SBATCH_SCRIPT:-${SCRIPT_DIR}/sbatch_eval_chess_passk_gh200.slurm}"
if [ ! -f "${BASE_EVAL_SBATCH_SCRIPT}" ]; then
  echo "[ERROR] Missing base eval sbatch script: ${BASE_EVAL_SBATCH_SCRIPT}" >&2
  exit 1
fi

RUN_ID="${CHESS_SFT_RUN_ID:-sft_prefix_ablation_$(date +%Y%m%d_%H%M%S)}"
echo "[SUBMIT] RUN_ID=${RUN_ID}"

CHESS_SFT_SBATCH_WAIT="${CHESS_SFT_SBATCH_WAIT:-1}"
SBATCH_WAIT_ARGS=()
if [[ "${CHESS_SFT_SBATCH_WAIT}" == "1" || "${CHESS_SFT_SBATCH_WAIT}" == "true" || "${CHESS_SFT_SBATCH_WAIT}" == "True" ]]; then
  SBATCH_WAIT_ARGS+=(--wait)
  echo "[SUBMIT] Blocking until completion (sbatch --wait)"
else
  echo "[SUBMIT] Non-blocking submit (override CHESS_SFT_SBATCH_WAIT=1 to block)"
fi

# Keep base + SFT eval settings aligned by driving them from the same env defaults here.
PROJECT_ROOT="${CHESS_RL_PROJECT_ROOT:-/projects/a5l/ziyan}"
MODEL_PATH="${MODEL_PATH:-Qwen/Qwen2.5-7B-Instruct}"
TEST_IN_PARQUET="${TEST_IN_PARQUET:-data/chess_puzzles/test.parquet}"
EVAL_K="${EVAL_K:-32}"
EVAL_SEED="${EVAL_SEED:-0}"
EVAL_SEED_MODE="${EVAL_SEED_MODE:-engine}"
EVAL_BATCH_SIZE="${EVAL_BATCH_SIZE:-32}"
EVAL_MAX_NUM_SEQS="${EVAL_MAX_NUM_SEQS:-1024}"
EVAL_MAX_RESPONSE_LENGTH="${EVAL_MAX_RESPONSE_LENGTH:-2000}"
EVAL_MAX_MODEL_LEN="${EVAL_MAX_MODEL_LEN:-4096}"
EVAL_GPU_MEMORY_UTILIZATION="${EVAL_GPU_MEMORY_UTILIZATION:-0.8}"
EVAL_TENSOR_PARALLEL_SIZE="${EVAL_TENSOR_PARALLEL_SIZE:-1}"

BASE_OUT_JSON="${BASE_OUT_JSON:-${PROJECT_ROOT%/}/chess_rl_outputs/${RUN_ID}/passk_base_k${EVAL_K}.json}"
echo "[SUBMIT] Base eval OUT_JSON=${BASE_OUT_JSON}"

SMOKE="${CHESS_SFT_SMOKE:-0}"
if [[ "${SMOKE}" == "1" || "${SMOKE}" == "true" || "${SMOKE}" == "True" ]]; then
  echo "[SUBMIT] Smoke mode enabled"
  # One variant, tiny model, tiny eval.
  SMOKE_MODEL_PATH="${SMOKE_MODEL_PATH:-Qwen/Qwen2.5-0.5B-Instruct}"
  SMOKE_EVAL_K="${SMOKE_EVAL_K:-2}"
  SMOKE_EVAL_LIMIT="${SMOKE_EVAL_LIMIT:-50}"
  SMOKE_TRAIN_LIMIT="${SMOKE_TRAIN_LIMIT:-64}"
  SMOKE_EVAL_BATCH_SIZE="${SMOKE_EVAL_BATCH_SIZE:-8}"
  SMOKE_EVAL_MAX_NUM_SEQS="${SMOKE_EVAL_MAX_NUM_SEQS:-128}"
  SMOKE_MAX_RESPONSE_LENGTH="${SMOKE_MAX_RESPONSE_LENGTH:-256}"
  SMOKE_MAX_MODEL_LEN="${SMOKE_MAX_MODEL_LEN:-1024}"

  (
    sbatch \
      "${SBATCH_WAIT_ARGS[@]}" \
      --job-name="chess-passk-base-smoke" \
      --export="ALL,MODEL=${SMOKE_MODEL_PATH},PARQUET=${TEST_IN_PARQUET},K_MAX=${SMOKE_EVAL_K},SEED=${EVAL_SEED},SEED_MODE=${EVAL_SEED_MODE},BATCH_SIZE=${SMOKE_EVAL_BATCH_SIZE},MAX_NUM_SEQS=${SMOKE_EVAL_MAX_NUM_SEQS},MAX_RESPONSE_LENGTH=${SMOKE_MAX_RESPONSE_LENGTH},MAX_MODEL_LEN=${SMOKE_MAX_MODEL_LEN},GPU_MEMORY_UTILIZATION=${EVAL_GPU_MEMORY_UTILIZATION},TENSOR_PARALLEL_SIZE=1,PRINT_PROMPT_EXAMPLES=2,OUT_JSON=${PROJECT_ROOT%/}/chess_rl_outputs/${RUN_ID}/passk_base_smoke_k${SMOKE_EVAL_K}.json" \
      "${BASE_EVAL_SBATCH_SCRIPT}"
  ) &

  (
    sbatch \
      "${SBATCH_WAIT_ARGS[@]}" \
      --array=0 \
      --job-name="chess-sft-prefix-smoke" \
      --export="ALL,CHESS_SFT_RUN_ID=${RUN_ID},MODEL_PATH=${SMOKE_MODEL_PATH},EVAL_K=${SMOKE_EVAL_K},EVAL_LIMIT=${SMOKE_EVAL_LIMIT},TRAIN_LIMIT=${SMOKE_TRAIN_LIMIT},EVAL_TENSOR_PARALLEL_SIZE=1,NPROC_PER_NODE=1,TRAIN_BATCH_SIZE=2,EVAL_BATCH_SIZE=${SMOKE_EVAL_BATCH_SIZE},EVAL_MAX_NUM_SEQS=${SMOKE_EVAL_MAX_NUM_SEQS},EVAL_MAX_RESPONSE_LENGTH=${SMOKE_MAX_RESPONSE_LENGTH},EVAL_MAX_MODEL_LEN=${SMOKE_MAX_MODEL_LEN}" \
      "${SBATCH_SCRIPT}"
  ) &

  wait
  exit 0
fi

(
  sbatch \
    "${SBATCH_WAIT_ARGS[@]}" \
    --job-name="chess-passk-base" \
    --export="ALL,MODEL=${MODEL_PATH},PARQUET=${TEST_IN_PARQUET},K_MAX=${EVAL_K},SEED=${EVAL_SEED},SEED_MODE=${EVAL_SEED_MODE},TEMPERATURE=0.6,TOP_P=0.95,BATCH_SIZE=${EVAL_BATCH_SIZE},MAX_NUM_SEQS=${EVAL_MAX_NUM_SEQS},MAX_PROMPT_LENGTH=1024,MAX_RESPONSE_LENGTH=${EVAL_MAX_RESPONSE_LENGTH},MAX_MODEL_LEN=${EVAL_MAX_MODEL_LEN},GPU_MEMORY_UTILIZATION=${EVAL_GPU_MEMORY_UTILIZATION},TENSOR_PARALLEL_SIZE=${EVAL_TENSOR_PARALLEL_SIZE},PRINT_PROMPT_EXAMPLES=2,OUT_JSON=${BASE_OUT_JSON}" \
    "${BASE_EVAL_SBATCH_SCRIPT}"
) &

(
  sbatch \
    "${SBATCH_WAIT_ARGS[@]}" \
    --job-name="chess-sft-prefix" \
    --export="ALL,CHESS_SFT_RUN_ID=${RUN_ID},MODEL_PATH=${MODEL_PATH},TEST_IN_PARQUET=${TEST_IN_PARQUET},EVAL_K=${EVAL_K},EVAL_SEED=${EVAL_SEED},EVAL_SEED_MODE=${EVAL_SEED_MODE},EVAL_BATCH_SIZE=${EVAL_BATCH_SIZE},EVAL_MAX_NUM_SEQS=${EVAL_MAX_NUM_SEQS},EVAL_MAX_RESPONSE_LENGTH=${EVAL_MAX_RESPONSE_LENGTH},EVAL_MAX_MODEL_LEN=${EVAL_MAX_MODEL_LEN},EVAL_GPU_MEMORY_UTILIZATION=${EVAL_GPU_MEMORY_UTILIZATION},EVAL_TENSOR_PARALLEL_SIZE=${EVAL_TENSOR_PARALLEL_SIZE}" \
    "${SBATCH_SCRIPT}"
) &

wait
